DROP TABLE Users;
DROP TABLE Images;

CREATE TABLE Images (
    Id INT PRIMARY KEY IDENTITY,
    Image VARBINARY(MAX)
);

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY,
    Username NVARCHAR(30) UNIQUE NOT NULL,
    Password NVARCHAR(64) NOT NULL,
    Email NVARCHAR(320) UNIQUE NOT NULL,
    Gender INT,
    Birthdate DATE,
    Country NVARCHAR(50),
    City NVARCHAR(50),
    ImageId INT,

    FOREIGN KEY (ImageId) REFERENCES Images(Id)
);
