DROP TABLE Tokens;
DROP TABLE Users;

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY,
    Username NVARCHAR(30) UNIQUE NOT NULL,
    Password NVARCHAR(64) NOT NULL,
    Salt NVARCHAR(32) NOT NULL,
    Email NVARCHAR(320) UNIQUE NOT NULL,
    Gender INT,
    Birthdate DATE,
    Country NVARCHAR(50),
    City NVARCHAR(50),
    Active BIT NOT NULL DEFAULT 0,
    ActivationCode NVARCHAR(64),
);

CREATE TABLE Tokens (
    Id INT PRIMARY KEY IDENTITY,
    Username NVARCHAR(30) NOT NULL,
    Token NVARCHAR(128) NOT NULL UNIQUE,
    Expiration DATETIME NOT NULL,
    FOREIGN KEY (Username) REFERENCES Users(Username)
);

SELECT * FROM Users;
SELECT * FROM Tokens;
